// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `book_format_type` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(std::fmt::Debug, diesel::query_builder::QueryId, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "book_format_type"))]
    pub struct BookFormatType;
}

diesel::table! {
    use diesel::sql_types::Varchar;
    use super::sql_types::BookFormatType;

    /// Representation of the `books` table.
    ///
    /// (Automatically generated by Diesel.)
    books (isbn) {
        /// The `title` column of the `books` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Varchar,
        /// The `author` column of the `books` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        author -> Varchar,
        /// The `format` column of the `books` table.
        ///
        /// Its SQL type is `BookFormatType`.
        ///
        /// (Automatically generated by Diesel.)
        format -> BookFormatType,
        /// The `isbn` column of the `books` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        isbn -> Varchar,
    }
}
