//! This crate implements a postgresql readonly api (only get handlers).
//! The ORM diesel.rs is used to generate the schema.

/// Module file for the app builder code.
pub mod builder;
/// Module file for establishing the database
pub mod db;
/// Module file for the types used in this crate.
pub mod models;
/// Module file for the schema generated by the ORM.
pub mod schema;

#[cfg(test)]
mod api_testing;

use builder::build_app;
use db::establish_connpool;
use diesel_derive_enum as _;
use dotenvy as _;
use serde_json as _;
use std::error::Error;
use tokio::net::TcpListener;
use tokio::runtime::Builder;
/// The entry point for the main function.
/// # Errors
/// Returns an error if the Tokio runtime cannot be initialized,
/// or if the application cannot bind to the specified address.
fn main() -> Result<(), Box<dyn Error>> {
    let runtime = Builder::new_multi_thread().enable_all().build()?;
    runtime.block_on(async_main())
}
/// The actual main function that has the async logic.
/// # Errors
/// Returns an error if:
/// -The `DATABASE_URL` environment variable is missing or not set.
/// -A connection pool to the database cannot be established
/// -Port 1919 is already in use.
async fn async_main() -> Result<(), Box<dyn Error>> {
    let pool = establish_connpool()?;
    let app = build_app(pool);

    let addrs = "127.0.0.1:1919";
    println!("App is listening on {addrs}");
    let listener = TcpListener::bind(addrs).await?;
    axum::serve(listener, app).await?;
    Ok(())
}
