//! Connector for `PostgreSQL` databases.

use async_trait::async_trait;
use diesel::PgConnection;
use diesel::r2d2::{ConnectionManager, Pool};
use diesel::result::Error as DslError;
use futures::stream::{self, BoxStream, StreamExt as _};
use std::io::Error;
use std::io::ErrorKind::ConnectionRefused;
use std::marker::PhantomData;
use std::slice::from_ref;
use tokio::task::spawn_blocking;

use crate::connector::{Sink, Source};
use crate::errors::{ConnectionError, EncodeError, FetchError, FetchOneError, SendError};
use crate::query::Query;
use diesel::QueryResult;

pub mod builder;
pub mod models;
/// Schema file generated by diesel
pub mod schema;

pub use builder::*;
pub use models::*;

// Database traits instead of byte-oriented Codec that can map directly to database rows.

/// Postgres decode
pub trait PgDecode<T> {
    /// Decodes data from a raw SQL string.
    ///
    /// # Errors
    ///
    /// Returns a `diesel::result::Error` if the database query fails or if
    /// the raw rows cannot be safely mapped to the target struct.
    fn decode_all(&self, conn: &mut PgConnection, sql_text: &str) -> Result<Vec<T>, DslError>;
    /// Fetches a single optional record from the database.
    ///
    /// # Errors
    /// Returns a `diesel::result::Error` if the database query fails.
    fn decode_optional(&self, conn: &mut PgConnection, sql_text: &str) -> QueryResult<Option<T>>;
}

/// Postgres encode
pub trait PgEncode<T> {
    /// Encodes and inserts data into the database.
    ///
    /// # Errors
    ///
    /// Returns a `diesel::result::Error` if the database insertion fails,
    /// such as from a constraint violation or network issue.
    fn encode_all(&self, conn: &mut PgConnection, entries: &[T]) -> QueryResult<usize>;
    /// Inserts a single record into the database.
    ///
    /// # Errors
    /// Returns a `diesel::result::Error` if the database rejects the insertion.
    fn encode_one(&self, conn: &mut PgConnection, entry: &T) -> QueryResult<usize>;
    /// Safely handles an optional insert.
    ///
    /// # Errors
    /// Returns a `diesel::result::Error` if the database rejects the insertion.
    fn encode_optional(&self, conn: &mut PgConnection, entry: Option<&T>) -> QueryResult<usize>;
}

/// Database connection pool
pub type PgPool = Pool<ConnectionManager<PgConnection>>;

#[derive(Debug, Clone)]
/// Struct for readonly connector
pub struct ReadOnly<T, D> {
    /// Database pool
    pub(crate) pool: PgPool,
    /// Decoder
    pub(crate) decoder: D,
    /// Phantomdata field
    pub(crate) _phantom: PhantomData<T>,
}

#[derive(Debug, Clone)]
/// Struct for writeonly connector
pub struct WriteOnly<T, E> {
    /// Database pool
    pub(crate) pool: PgPool,
    /// Encoder
    pub(crate) encoder: E,
    /// Phantomdata field
    pub(crate) _phantom: PhantomData<T>,
}

#[derive(Debug, Clone)]
/// Readwrite connector
pub struct ReadWrite<T, E, D> {
    /// Database pool
    pub(crate) pool: PgPool,
    /// Encoder
    pub(crate) encoder: E,
    /// Decoder
    pub(crate) decoder: D,
    /// Phantomdata field
    pub(crate) _phantom: PhantomData<T>,
}

#[async_trait]
impl<T, D> Source<T> for ReadOnly<T, D>
where
    T: Send + Sync + 'static,
    D: PgDecode<T> + Clone + Send + Sync + 'static,
{
    #[inline]
    async fn fetch_all(&mut self, query: &(dyn Query<T> + Sync)) -> Result<Vec<T>, FetchError> {
        let single = query.to_sql_single();
        let sql_text = single.query.query_text;
        let residue = single.residue;

        let pool = self.pool.clone();
        let decoder = self.decoder.clone();

        let mut decoded_items = spawn_blocking(move || {
            let mut conn = pool
                .get()
                .map_err(|e| FetchError::InvalidQuery(Box::new(e)))?;

            decoder
                .decode_all(&mut conn, &sql_text)
                .map_err(|e| FetchError::InvalidQuery(Box::new(e)))
        })
        .await
        .expect("Tokio background thread panicked")?;

        // Evaluate any fallback residue
        decoded_items.retain(|item| residue.iter().all(|r| r.evaluate(item)));

        Ok(decoded_items)
    }
    #[inline]
    async fn fetch_one(&mut self, query: &(dyn Query<T> + Sync)) -> Result<T, FetchOneError> {
        let items = self.fetch_all(query).await.map_err(FetchOneError::Fetch)?;

        items.into_iter().next().ok_or(FetchOneError::NoSuchEntry)
    }
    #[inline]
    async fn fetch<'s>(
        &'s mut self,
        query: &'s (dyn Query<T> + Sync),
    ) -> Result<BoxStream<'s, Result<T, FetchError>>, FetchError>
    where
        T: 's,
    {
        let items = self.fetch_all(query).await?;

        // Convert the fetched vector into an asynchronous stream
        let stream = stream::iter(items.into_iter().map(Ok)).boxed();
        Ok(stream)
    }
}

#[async_trait]
impl<T, E> Sink<T> for WriteOnly<T, E>
where
    T: Clone + Sync + Send + 'static,
    E: PgEncode<T> + Clone + Send + Sync + 'static,
{
    #[inline]
    async fn send_all(&self, entries: &[T]) -> Result<(), SendError> {
        let pool = self.pool.clone();
        let encoder = self.encoder.clone();
        let entries_to_insert = entries.to_vec();

        spawn_blocking(move || -> Result<(), SendError> {
            let mut conn = pool.get().map_err(|e| {
                let io_err = Error::new(ConnectionRefused, e.to_string());
                SendError::Connection(ConnectionError::Io(io_err))
            })?;

            let _ = encoder
                .encode_all(&mut conn, &entries_to_insert)
                .map_err(|e| {
                    let boxed_err = Box::new(e);

                    SendError::Encode(EncodeError(boxed_err))
                })?;

            Ok(())
        })
        .await
        .expect("Tokio background thread panicked")?;

        Ok(())
    }
    #[inline]
    async fn send_one(&self, entry: &T) -> Result<(), SendError> {
        // Safely wrap the single entry in a slice without allocating a new Vec
        self.send_all(from_ref(entry)).await
    }
}

#[async_trait]
impl<T, E, D> Source<T> for ReadWrite<T, E, D>
where
    T: Send + Sync + 'static,
    D: PgDecode<T> + Clone + Send + Sync + 'static,
    E: Send + Sync + 'static,
{
    #[inline]
    async fn fetch_all(&mut self, query: &(dyn Query<T> + Sync)) -> Result<Vec<T>, FetchError> {
        let single = query.to_sql_single();
        let sql_text = single.query.query_text;
        let residue = single.residue;

        let pool = self.pool.clone();
        let decoder = self.decoder.clone();

        let mut decoded_items = spawn_blocking(move || {
            let mut conn = pool
                .get()
                .map_err(|e| FetchError::InvalidQuery(Box::new(e)))?;

            decoder
                .decode_all(&mut conn, &sql_text)
                .map_err(|e| FetchError::InvalidQuery(Box::new(e)))
        })
        .await
        .expect("Tokio background thread panicked")?;

        decoded_items.retain(|item| residue.iter().all(|r| r.evaluate(item)));

        Ok(decoded_items)
    }
    #[inline]
    async fn fetch_one(&mut self, query: &(dyn Query<T> + Sync)) -> Result<T, FetchOneError> {
        let items = self.fetch_all(query).await.map_err(FetchOneError::Fetch)?;
        items.into_iter().next().ok_or(FetchOneError::NoSuchEntry)
    }
    #[inline]
    async fn fetch<'s>(
        &'s mut self,
        query: &'s (dyn Query<T> + Sync),
    ) -> Result<BoxStream<'s, Result<T, FetchError>>, FetchError>
    where
        T: 's,
    {
        let items = self.fetch_all(query).await?;
        Ok(stream::iter(items.into_iter().map(Ok)).boxed())
    }
}

#[async_trait]
impl<T, E, D> Sink<T> for ReadWrite<T, E, D>
where
    T: Clone + Send + Sync + 'static,
    E: PgEncode<T> + Clone + Send + Sync + 'static,
    D: Send + Sync + 'static,
{
    #[inline]
    async fn send_all(&self, entries: &[T]) -> Result<(), SendError> {
        let pool = self.pool.clone();
        let encoder = self.encoder.clone();
        let entries_to_insert = entries.to_vec();

        spawn_blocking(move || -> Result<(), SendError> {
            let mut conn = pool.get().map_err(|e| {
                let io_err = Error::new(ConnectionRefused, e.to_string());

                SendError::Connection(ConnectionError::Io(io_err))
            })?;

            let _ = encoder
                .encode_all(&mut conn, &entries_to_insert)
                .map_err(|e| {
                    let boxed_err = Box::new(e);

                    SendError::Encode(EncodeError(boxed_err))
                })?;

            Ok(())
        })
        .await
        .expect("Tokio background thread panicked")?;

        Ok(())
    }
    #[inline]
    async fn send_one(&self, entry: &T) -> Result<(), SendError> {
        self.send_all(from_ref(entry)).await
    }
}
