//! The query API.

pub use query_macro::Queryable;

/// Query primitives and combinators.
mod combinators;
pub use combinators::*;

/// Translation of queries into other formats.
mod translate;
pub use translate::*;

/// A field of a struct.
///
/// Instances of this type are created using methods generated by deriving [`Queryable`] on the
/// struct.
#[derive(Debug, Clone, Copy)]
pub struct Field<T, U: ?Sized, const NAME: &'static str> {
    /// The getter function; accepts an instance of the struct and returns the appropriate field.
    getter: fn(&T) -> &U,
}

impl<T, U: PartialEq + ?Sized, const NAME: &'static str> Field<T, U, NAME> {
    /// Specifies that the field should be equal to `value`.
    #[inline]
    pub const fn eq(self, value: &U) -> Eq<'_, Self, U> {
        Eq { field: self, value }
    }

    /// Specifies that the field should not be equal to `value`.
    #[inline]
    pub const fn ne(self, value: &U) -> Ne<'_, Self, U> {
        Ne { field: self, value }
    }
}

impl<T, U: PartialOrd + ?Sized, const NAME: &'static str> Field<T, U, NAME> {
    /// Specifies that the field should be greater than `value`.
    #[inline]
    pub const fn gt(self, value: &U) -> Gt<'_, Self, U> {
        Gt { field: self, value }
    }

    /// Specifies that the field should be lesser than `value`.
    #[inline]
    pub const fn lt(self, value: &U) -> Lt<'_, Self, U> {
        Lt { field: self, value }
    }
}

// TODO: Add compilation tests besides normal unit tests.
